name: login
description: Microfrontend de autenticaci贸n en Flutter.
publish_to: 'none' # Este paquete no se publicar谩

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #  Manejo de rutas (igual que en chasis para compatibilidad)
  go_router: ^10.2.0  

  #  Cliente HTTP para autenticaci贸n
  dio: ^5.4.0
  http: ^0.13.6  # Solo si hay dependencias que lo requieran

  #  Manejo de estado con BLoC
  flutter_bloc: ^8.1.3
  provider: ^6.0.5

  #  Manejo de JSON
  json_annotation: ^4.8.1

  #  Almacenamiento seguro (para credenciales)
  flutter_secure_storage: ^9.2.0
  shared_preferences: ^2.2.2

  #  Firebase para autenticaci贸n (si se requiere)
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2

  #  Registro de logs
  logger: ^2.0.2+1

  #  Inyecci贸n de dependencias
  get_it: ^7.6.0

  #  Comparaci贸n eficiente de estados en Bloc
  equatable: ^2.0.5

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

  #  Generaci贸n de c贸digo para JSON
  build_runner: ^2.4.4
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
